[theme]
primaryColor = "#0f766e"
backgroundColor = "#eef2f6"
secondaryBackgroundColor = "#ffffff"
textColor = "#0f172a"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "viewer"
